version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: zip -r build app.js apps/ config/ static/ src/ webhook.js webhook-utils.js package*.json 
  deploy:
    docker:
      - image: instrumentisto/rsync-ssh
    steps:
      - run: echo $SSH_REMOTE_HOST_KEY >> ~/.ssh/known_hosts
      - add_ssh_key:
        fingerprints:
          - "54:b0:81:a1:46:6d:9d:26:a3:c5:cc:9f:6a:df:b1:32"
      - run: echo Here
      - run: which rsync

workflows:
  version: 2
  build_then_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: wpf-circleci

