version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: zip -r build app.js apps/ config/ static/ src/ webhook.js webhook-utils.js package*.json node_modules
      - persist_to_workspace:
          root: .
          paths:
            - build.zip
      - store_artifacts:
          path: build.zip
  deploy:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: mkdir -p ~/.ssh/
      - run: echo $SSH_REMOTE_HOSTKEY | base64 --decode >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "71:03:6c:64:dd:99:38:c4:bb:ce:07:de:51:32:51:69"
      - run: ssh $SSH_REMOTE_HOST mkdir membership-system/$CIRCLE_BUILD_NUM
      - run: scp /tmp/workspace/build.zip $SSH_REMOTE_HOST:membership-system/$CIRCLE_BUILD_NUM
      - run: ssh $SSH_REMOTE_HOST $CIRCLE_BUILD_NUM >membership-system.pipe

workflows:
  version: 2
  build_then_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: wpf-circleci

