version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: zip -r build app.js apps/ config/ static/ src/ webhook.js webhook-utils.js package*.json 
  deploy:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - run: apt-get install -y rsync
      - run: echo Here

workflows:
  version: 2
  build_then_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: wpf-circleci

