name: Deploy

on:
  push:
    branches: ["master", "dev"]

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.setvars.outputs.stage }}
    steps:
      - id: setvars
        run: |
          case "${{ github.ref }}" in
            refs/heads/master)
              echo "stage=latest" >> $GITHUB_OUTPUT
              ;;
            refs/heads/dev)
              echo "stage=dev" >> $GITHUB_OUTPUT
              ;;
          esac

  check:
    uses: ./.github/workflows/check.yml

  push:
    runs-on: ubuntu-latest
    needs: [init, check]
    steps:
      - uses: actions/checkout@v3
      - id: getrev
        run: |
          echo "revision=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          target: app
          build-args: |
            REVISION=${{ steps.getrev.outputs.revision }}
          tags: ${{ secrets.DOCKER_ORGANISATION }}/beabee:${{ needs.init.outputs.stage }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          target: router
          tags: ${{ secrets.DOCKER_ORGANISATION }}/router:${{ needs.init.outputs.stage }}

  deploy:
    runs-on: ubuntu-latest
    needs: [init, push]
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - run: ssh ${{ secrets.DEPLOY_SERVER }} ${{ needs.init.outputs.stage }}
