name: Deploy live

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - run: npm ci
      - run: cp src/config/example-config.json src/config/config.json
      - run: npm run checkDependencies
  push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            REVISION=${{ steps.short-sha.outputs.sha }}
          tags: beabee/beabee:latest

