name: Deploy

on:
  push:
    branches: ["master", "dev", "release"]

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.setvars.outputs.stage }}
    steps:
      - id: setvars
        run: |
          case "${{ github.ref }}" in
            refs/heads/master)
              echo "stage=latest" >> $GITHUB_OUTPUT
              ;;
            refs/heads/dev)
              echo "stage=dev" >> $GITHUB_OUTPUT
              ;;
            refs/heads/release)
              echo "stage=release" >> $GITHUB_OUTPUT
              ;;
          esac

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13
      - run: npm install dpdm
      - run: npm run checkDependencies
      - run: npx prettier --check .

  push:
    runs-on: ubuntu-latest
    needs: [init, test]
    steps:
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          target: app
          build-args: |
            REVISION=${{ steps.short-sha.outputs.sha }}
          tags: ${{ secrets.DOCKER_ORGANISATION }}/beabee:${{ needs.init.outputs.stage }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          target: router
          tags: ${{ secrets.DOCKER_ORGANISATION }}/router:${{ needs.init.outputs.stage }}

  deploy:
    runs-on: ubuntu-latest
    needs: [init, push]
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - run: ssh ${{ secrets.DEPLOY_SERVER }} ${{ needs.init.outputs.stage }}
