name: Release

on:
  push:
    branches:
      - feat/*

jobs:
  check:
    uses: ./.github/workflows/check.yml

  push:
    runs-on: ubuntu-latest
    needs: [check]

    outputs:
      version: ${{ fromJSON(steps.app_meta.outputs.json).labels['org.opencontainers.image.version'] }}

    steps:
      - uses: actions/checkout@v3

      - id: app_meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
          images: |
            ${{ secrets.DOCKER_ORGANISATION }}/beabee-test
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            test

      - id: router_meta
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
          images: |
            ${{ secrets.DOCKER_ORGANISATION }}/beabee-router-test
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            test

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          target: app
          push: true
          tags: ${{ steps.app_meta.outputs.tags }}
          labels: ${{ steps.app_meta.outputs.labels }}
          build-args: |
            REVISION=${{ fromJSON(steps.app_meta.outputs.json).labels['org.opencontainers.image.revision'] }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          target: router
          push: true
          tags: ${{ steps.router_meta.outputs.tags }}
          labels: ${{ steps.router_meta.outputs.labels }}
          build-args: |
            REVISION=${{ fromJSON(steps.router_meta.outputs.json).labels['org.opencontainers.image.revision'] }}

      - uses: docker/build-push-action@v4

  deploy:
    runs-on: ubuntu-latest
    needs: [push]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: beabee-communityrm/test-deploy
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - run: |
          git config --global user.name "Deploy bot"
          git config --global user.email "<>"

          echo -n ${{ needs.push.outputs.version }} > API_VERSION
          ./update.sh

          git add API_VERSION docker-compose.yml
          if ! git diff --quiet --cached; then
            git commit -m "Deploy ${{ needs.push.outputs.version }}"
            git push
          fi
